name: "TOML Sort"
author: "Off-Narrative Labs"
description: "Sort and format TOML files"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  files:
    description: "List of files to check, if all is unset. Default is Cargo.toml."
    required: true
    default: "Cargo.toml"
  all:
    description: "Performs check on all the TOML files it can find, starting from current directory."
    required: true
    default: false
  match:
    description: "If all is set, performs checks on all the TOML files it can find that match this string."
    required: true
    default: "*.toml"

runs:
  using: "composite"
  steps:
    - name: "Installing TOML Sort"
      shell: "bash"
      run: curl https://github.com/Off-Narrative-Labs/toml_sort/releases/download/v1.1.0/toml-sort-x86_64-unknown-linux-gnu.tar.gz -L | tar -xz
    - if: ${{ inputs.all }}
      name: "Running TOML Sort check"
      shell: "bash"
      run: find . -type f -iname "${{ inputs.match }}" -not -path "./target/*" | xargs -L1 ./toml-sort --check
    - if: ${{ !inputs.all }}
      name: "Running TOML Sort check"
      shell: "bash"
      run: ./toml-sort --check {{ inputs.files }}
      
