name: "TOML Sort"
author: "Off-Narrative Labs"
description: "Sort and format TOML files"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  files:
    description: "Files to check, default is Cargo.toml"
    required: true
    default: "Cargo.toml"
  all:
    description: "Performs check on all the TOML files it can find starting from current directory"
    required: true
    default: false

runs:
  using: "composite"
  steps:
    - name: "Installing TOML Sort"
      shell: "bash"
      run: curl https://github.com/Off-Narrative-Labs/toml_sort/releases/download/v1.0.0/toml-sort-x86_64-unknown-linux-gnu.tar.gz -L | tar -xz
    - if: ${{ inputs.all }}
      name: "Running TOML Sort check on all TOML files starting from current directory"
      shell: "bash"
      run: find . -name "*.toml" -not -path "./target/*" | xargs -L1 ./toml-sort --check
    - if: ${{ !inputs.all }}
      name: "Running TOML Sort check on given files"
      shell: "bash"
      run: ./toml-sort --check {{ inputs.files }}
      
